@isTest(seeAllData=true)
public class Comentar_test {
  //Comentario 1 
  //Comentario 2
  @isTest static void IT_FamiEmpresaHandler_cls(){
        IT_FamiEmpresaHandler_cls fami = new IT_FamiEmpresaHandler_cls();
    }
    
    @isTest static void IT_GestorDeConsultas_cls(){
       // IT_GestorDeConsultas_cls ins = new IT_GestorDeConsultas_cls();
    }
    
    // @isTest static void IT_ServicioCliente_cls(){
    //     IT_ServicioCliente_cls ins = new IT_ServicioCliente_cls();
    // }

    @isTest static void IT_ServicioOportunidad_ws(){
        IT_ServicioOportunidad_ws ins = new IT_ServicioOportunidad_ws();
    }
}
